/*
 * Rate labels vs Indexes to data arrays passed through IOV
 * $Copyright (C) 2011 Broadcom Corporation$
 */
/*FILE-CSTYLED*/

#ifndef _WLU_RATES_MATRIX_H_
#define _WLU_RATES_MATRIX_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <wlc_clm_rates.h>
#include <wlioctl.h>
#include <typedefs.h>
#include <epivers.h>
#include <bcmutils.h>
#include <bcmendian.h>
#include <bcmwifi.h>

#ifdef LINUX
#include <inttypes.h>
#endif
#include <miniopt.h>

#ifdef PPR_API
#include <wlc_ppr.h>
#endif

#define WL_UNSUPPORTED_IDX 0xFF

typedef enum clm_rate_group_id {
	RATE_GROUP_ID_DSSS = 0,
	RATE_GROUP_ID_OFDM,
	RATE_GROUP_ID_MCS0_7,
	RATE_GROUP_ID_DSSS_MULTI1,
	RATE_GROUP_ID_OFDM_CDD1,
	RATE_GROUP_ID_MCS0_7_CDD1,
	RATE_GROUP_ID_MCS0_7_STBC,
	RATE_GROUP_ID_MCS8_15,
	RATE_GROUP_ID_DSSS_MULTI2,
	RATE_GROUP_ID_OFDM_CDD2,
	RATE_GROUP_ID_MCS0_7_CDD2,
	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1,
	RATE_GROUP_ID_MCS8_15_SPEXP1,
	RATE_GROUP_ID_MCS16_23,
	RATE_GROUP_ID_COUNT
} clm_rate_group_id_t;

#ifdef PPR_API
typedef enum ppr_rate_type {
	PPR_RATE_DSSS,
	PPR_RATE_OFDM,
	PPR_RATE_HT,
} ppr_rate_type_t;

typedef struct {
	clm_rate_group_id_t id;
	ppr_rate_type_t type;
	wl_tx_chains_t chains;
	wl_tx_mode_t mode;
	wl_tx_nss_t nss;
} rate_group_type_t;

static const rate_group_type_t rate_type_tbl[] = {
	{ RATE_GROUP_ID_DSSS, PPR_RATE_DSSS, WL_TX_CHAINS_1, WL_TX_MODE_NONE, WL_TX_NSS_1},
	{ RATE_GROUP_ID_OFDM, PPR_RATE_OFDM, WL_TX_CHAINS_1, WL_TX_MODE_NONE, WL_TX_NSS_1},
	{ RATE_GROUP_ID_MCS0_7, PPR_RATE_HT, WL_TX_CHAINS_1, WL_TX_MODE_NONE, WL_TX_NSS_1},
	{ RATE_GROUP_ID_DSSS_MULTI1, PPR_RATE_DSSS, WL_TX_CHAINS_2, WL_TX_MODE_NONE, WL_TX_NSS_1},
	{ RATE_GROUP_ID_OFDM_CDD1, PPR_RATE_OFDM, WL_TX_CHAINS_2, WL_TX_MODE_CDD, WL_TX_NSS_1},
	{ RATE_GROUP_ID_MCS0_7_CDD1, PPR_RATE_HT, WL_TX_CHAINS_2, WL_TX_MODE_CDD, WL_TX_NSS_1},
	{ RATE_GROUP_ID_MCS0_7_STBC, PPR_RATE_HT, WL_TX_CHAINS_2, WL_TX_MODE_STBC, WL_TX_NSS_2},
	{ RATE_GROUP_ID_MCS8_15, PPR_RATE_HT, WL_TX_CHAINS_2, WL_TX_MODE_NONE, WL_TX_NSS_2},
	{ RATE_GROUP_ID_DSSS_MULTI2, PPR_RATE_DSSS, WL_TX_CHAINS_3, WL_TX_MODE_NONE, WL_TX_NSS_2},
	{ RATE_GROUP_ID_OFDM_CDD2, PPR_RATE_OFDM, WL_TX_CHAINS_3, WL_TX_MODE_CDD, WL_TX_NSS_2},
	{ RATE_GROUP_ID_MCS0_7_CDD2, PPR_RATE_HT, WL_TX_CHAINS_3, WL_TX_MODE_CDD, WL_TX_NSS_2},
	{ RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, PPR_RATE_HT, WL_TX_CHAINS_3, WL_TX_MODE_STBC, WL_TX_NSS_2},
	{ RATE_GROUP_ID_MCS8_15_SPEXP1, PPR_RATE_HT, WL_TX_CHAINS_3, WL_TX_MODE_NONE, WL_TX_NSS_2},
	{ RATE_GROUP_ID_MCS16_23, PPR_RATE_HT, WL_TX_CHAINS_3, WL_TX_MODE_NONE, WL_TX_NSS_3},
};

#endif

typedef struct {
    char label[20];
    uint8 streams;
    uint8 chains;
    clm_rate_group_id_t id;
    clm_rates_t rate;
    uint8 bw20ssl;
    uint8 bw20n;
    uint8 bw20ht;
    uint8 bw40ssl;
    uint8 bw40n;
    uint8 bw40ht;
    uint8 bw20in40ssl;
    uint8 bw20in40n;
    uint8 bw20in40ht;
} clm_rate_matrix_t;

#ifndef ATE_BUILD
static const char *clm_rate_group_labels[] = {
	"DSSS",
	"OFDM",
	"MCS0_7",
	"DSSS_MULTI1",
	"OFDM_CDD1",
	"MCS0_7_CDD1",
	"MCS0_7_STBC",
	"MCS8_15",
	"DSSS_MULTI2",
	"OFDM_CDD2",
	"MCS0_7_CDD2",
	"MCS0_7_STBC_SPEXP1",
	"MCS8_15_SPEXP1",
	"MCS16_23"
};
#endif /* ATE_BUILD */


static const clm_rate_matrix_t rate_matrix[] = {
	/* Label   Stream			Rate Group ID						CLM Index					20MHz SISO								20MHz N									20MHz HT								40MHz SISO								40MHz N								40MHz HT							20in40MHz SISO							20in40MHz N									20in40MHz HT */
	{"DSSS1", 1, 1, 			RATE_GROUP_ID_DSSS, 				CLM_RATE_1X1_DSSS_1, 		WL_TX_POWER_CCK_FIRST, 					WL_TX_POWER_CCK_FIRST, 					WL_TX_POWER_CCK_FIRST, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX, 				WL_TX_POWER_CCK_FIRST, 					WL_TX_POWER_20UL_CCK_FIRST,					WL_TX_POWER_20UL_CCK_FIRST},
	{"DSSS2", 1, 1, 			RATE_GROUP_ID_DSSS, 				CLM_RATE_1X1_DSSS_2, 		WL_TX_POWER_CCK_FIRST + 1,				WL_TX_POWER_CCK_FIRST + 1, 				WL_TX_POWER_CCK_FIRST + 1, 				WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX, 		 		WL_TX_POWER_CCK_FIRST + 1,				WL_TX_POWER_20UL_CCK_FIRST + 1,				WL_TX_POWER_20UL_CCK_FIRST + 1},
	{"DSSS5", 1, 1, 			RATE_GROUP_ID_DSSS, 				CLM_RATE_1X1_DSSS_5_5, 		WL_TX_POWER_CCK_FIRST + 2,				WL_TX_POWER_CCK_FIRST + 2, 				WL_TX_POWER_CCK_FIRST + 2, 				WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX, 		 		WL_TX_POWER_CCK_FIRST + 2,				WL_TX_POWER_20UL_CCK_FIRST + 2,				WL_TX_POWER_20UL_CCK_FIRST + 2},
	{"DSSS11", 1, 1, 			RATE_GROUP_ID_DSSS, 				CLM_RATE_1X1_DSSS_11, 		WL_TX_POWER_CCK_FIRST + 3,				WL_TX_POWER_CCK_FIRST + 3, 				WL_TX_POWER_CCK_FIRST + 3, 				WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX, 		 		WL_TX_POWER_CCK_FIRST + 3,				WL_TX_POWER_20UL_CCK_FIRST + 3,				WL_TX_POWER_20UL_CCK_FIRST + 3},
	{"OFDM6", 1, 1, 			RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_6, 		WL_TX_POWER_OFDM20_FIRST,				WL_TX_POWER_OFDM20_FIRST, 				WL_TX_POWER_OFDM20_FIRST, 				WL_TX_POWER_OFDM20_FIRST,				WL_TX_POWER_OFDM40_FIRST, 	 	 	WL_TX_POWER_OFDM40_FIRST, 			WL_TX_POWER_OFDM20_FIRST,				WL_TX_POWER_20UL_OFDM_FIRST,				WL_TX_POWER_20UL_OFDM_FIRST},
	{"OFDM9", 1, 1, 			RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_9, 		WL_TX_POWER_OFDM20_FIRST + 1,			WL_TX_POWER_OFDM20_FIRST + 1, 			WL_TX_POWER_OFDM20_FIRST + 1, 			WL_TX_POWER_OFDM20_FIRST + 1,			WL_TX_POWER_OFDM40_FIRST + 1, 	 	WL_TX_POWER_OFDM40_FIRST + 1, 		WL_TX_POWER_OFDM20_FIRST + 1,			WL_TX_POWER_20UL_OFDM_FIRST + 1,			WL_TX_POWER_20UL_OFDM_FIRST + 1},
	{"OFDM12", 1, 1, 			RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_12, 		WL_TX_POWER_OFDM20_FIRST + 2,			WL_TX_POWER_OFDM20_FIRST + 2, 			WL_TX_POWER_OFDM20_FIRST + 2, 			WL_TX_POWER_OFDM20_FIRST + 2,			WL_TX_POWER_OFDM40_FIRST + 2, 	 	WL_TX_POWER_OFDM40_FIRST + 2, 		WL_TX_POWER_OFDM20_FIRST + 2,			WL_TX_POWER_20UL_OFDM_FIRST + 2,			WL_TX_POWER_20UL_OFDM_FIRST + 2},
	{"OFDM18", 1, 1, 			RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_18, 		WL_TX_POWER_OFDM20_FIRST + 3,			WL_TX_POWER_OFDM20_FIRST + 3, 			WL_TX_POWER_OFDM20_FIRST + 3, 			WL_TX_POWER_OFDM20_FIRST + 3,			WL_TX_POWER_OFDM40_FIRST + 3, 	 	WL_TX_POWER_OFDM40_FIRST + 3, 		WL_TX_POWER_OFDM20_FIRST + 3,			WL_TX_POWER_20UL_OFDM_FIRST + 3,			WL_TX_POWER_20UL_OFDM_FIRST + 3},
	{"OFDM24", 1, 1, 			RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_24, 		WL_TX_POWER_OFDM20_FIRST + 4,			WL_TX_POWER_OFDM20_FIRST + 4, 			WL_TX_POWER_OFDM20_FIRST + 4, 			WL_TX_POWER_OFDM20_FIRST + 4,			WL_TX_POWER_OFDM40_FIRST + 4,		WL_TX_POWER_OFDM40_FIRST + 4, 		WL_TX_POWER_OFDM20_FIRST + 4,			WL_TX_POWER_20UL_OFDM_FIRST + 4,			WL_TX_POWER_20UL_OFDM_FIRST + 4},
	{"OFDM36", 1, 1,	 		RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_36, 		WL_TX_POWER_OFDM20_FIRST + 5,			WL_TX_POWER_OFDM20_FIRST + 5, 			WL_TX_POWER_OFDM20_FIRST + 5, 			WL_TX_POWER_OFDM20_FIRST + 5,			WL_TX_POWER_OFDM40_FIRST + 5,		WL_TX_POWER_OFDM40_FIRST + 5, 		WL_TX_POWER_OFDM20_FIRST + 5,			WL_TX_POWER_20UL_OFDM_FIRST + 5,			WL_TX_POWER_20UL_OFDM_FIRST + 5},
	{"OFDM48", 1, 1, 			RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_48, 		WL_TX_POWER_OFDM20_FIRST + 6,			WL_TX_POWER_OFDM20_FIRST + 6, 			WL_TX_POWER_OFDM20_FIRST + 6, 			WL_TX_POWER_OFDM20_FIRST + 6,			WL_TX_POWER_OFDM40_FIRST + 6,		WL_TX_POWER_OFDM40_FIRST + 6, 		WL_TX_POWER_OFDM20_FIRST + 6,			WL_TX_POWER_20UL_OFDM_FIRST + 6,			WL_TX_POWER_20UL_OFDM_FIRST + 6},
	{"OFDM54", 1, 1, 			RATE_GROUP_ID_OFDM, 				CLM_RATE_1X1_OFDM_54, 		WL_TX_POWER_OFDM20_FIRST + 7,			WL_TX_POWER_OFDM20_FIRST + 7, 			WL_TX_POWER_OFDM20_FIRST + 7, 			WL_TX_POWER_OFDM20_FIRST + 7,			WL_TX_POWER_OFDM40_FIRST + 7,		WL_TX_POWER_OFDM40_FIRST + 7, 		WL_TX_POWER_OFDM20_FIRST + 7,			WL_TX_POWER_20UL_OFDM_FIRST + 7,			WL_TX_POWER_20UL_OFDM_FIRST + 7},
	{"MCS0", 1, 1, 				RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS0, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN,		WL_TX_POWER_MCS20_SISO_FIRST, 			WL_TX_POWER_20_S1x1_FIRST, 				WL_TX_POWER_MCS40_SISO_FIRST_SSN,		WL_TX_POWER_MCS40_SISO_FIRST, 		WL_TX_POWER_40_S1x1_FIRST, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN,		WL_TX_POWER_20UL_S1x1_FIRST,				WL_TX_POWER_20UL_S1x1_FIRST},
	{"MCS1", 1, 1, 				RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS1, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN + 1,	WL_TX_POWER_MCS20_SISO_FIRST + 1, 		WL_TX_POWER_20_S1x1_FIRST + 1, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN + 1,	WL_TX_POWER_MCS40_SISO_FIRST + 1,	WL_TX_POWER_40_S1x1_FIRST + 1, 		WL_TX_POWER_MCS40_SISO_FIRST_SSN + 1,	WL_TX_POWER_20UL_S1x1_FIRST + 1,			WL_TX_POWER_20UL_S1x1_FIRST + 1},
	{"MCS2", 1, 1, 				RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS2, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN + 2,	WL_TX_POWER_MCS20_SISO_FIRST + 2, 		WL_TX_POWER_20_S1x1_FIRST + 2, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN + 2,	WL_TX_POWER_MCS40_SISO_FIRST + 2,	WL_TX_POWER_40_S1x1_FIRST + 2, 		WL_TX_POWER_MCS40_SISO_FIRST_SSN + 2,	WL_TX_POWER_20UL_S1x1_FIRST + 2,			WL_TX_POWER_20UL_S1x1_FIRST + 2},
	{"MCS3", 1, 1, 				RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS3, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN + 3,	WL_TX_POWER_MCS20_SISO_FIRST + 3, 		WL_TX_POWER_20_S1x1_FIRST + 3, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN + 3,	WL_TX_POWER_MCS40_SISO_FIRST + 3,	WL_TX_POWER_40_S1x1_FIRST + 3, 		WL_TX_POWER_MCS40_SISO_FIRST_SSN + 3,	WL_TX_POWER_20UL_S1x1_FIRST + 3,			WL_TX_POWER_20UL_S1x1_FIRST + 3},
	{"MCS4", 1, 1, 				RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS4, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN + 4,	WL_TX_POWER_MCS20_SISO_FIRST + 4, 		WL_TX_POWER_20_S1x1_FIRST + 4, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN + 4,	WL_TX_POWER_MCS40_SISO_FIRST + 4,	WL_TX_POWER_40_S1x1_FIRST + 4, 		WL_TX_POWER_MCS40_SISO_FIRST_SSN + 4,	WL_TX_POWER_20UL_S1x1_FIRST + 4,			WL_TX_POWER_20UL_S1x1_FIRST + 4},
	{"MCS5", 1, 1, 				RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS5, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN + 5,	WL_TX_POWER_MCS20_SISO_FIRST + 5, 		WL_TX_POWER_20_S1x1_FIRST + 5, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN + 5,	WL_TX_POWER_MCS40_SISO_FIRST + 5,	WL_TX_POWER_40_S1x1_FIRST + 5, 		WL_TX_POWER_MCS40_SISO_FIRST_SSN + 5,	WL_TX_POWER_20UL_S1x1_FIRST + 5,			WL_TX_POWER_20UL_S1x1_FIRST + 5},
	{"MCS6", 1, 1,	 			RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS6, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN + 6,	WL_TX_POWER_MCS20_SISO_FIRST + 6, 		WL_TX_POWER_20_S1x1_FIRST + 6, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN + 6,	WL_TX_POWER_MCS40_SISO_FIRST + 6,	WL_TX_POWER_40_S1x1_FIRST + 6, 		WL_TX_POWER_MCS40_SISO_FIRST_SSN + 6,	WL_TX_POWER_20UL_S1x1_FIRST + 6,			WL_TX_POWER_20UL_S1x1_FIRST + 6},
	{"MCS7", 1, 1, 				RATE_GROUP_ID_MCS0_7, 				CLM_RATE_1X1_MCS7, 			WL_TX_POWER_MCS20_SISO_FIRST_SSN + 7,	WL_TX_POWER_MCS20_SISO_FIRST + 7, 		WL_TX_POWER_20_S1x1_FIRST + 7, 			WL_TX_POWER_MCS40_SISO_FIRST_SSN + 7,	WL_TX_POWER_MCS40_SISO_FIRST + 7,	WL_TX_POWER_40_S1x1_FIRST + 7, 		WL_TX_POWER_MCS40_SISO_FIRST_SSN + 7,	WL_TX_POWER_20UL_S1x1_FIRST + 7,			WL_TX_POWER_20UL_S1x1_FIRST + 7},
	{"DSSS1_MULTI1", 1, 2, 		RATE_GROUP_ID_DSSS_MULTI1, 			CLM_RATE_1X2_DSSS_1, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x2_FIRST, 		WL_TX_POWER_CCK_CDD_S1x2_FIRST, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST,			WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST},
	{"DSSS2_MULTI1", 1, 2, 		RATE_GROUP_ID_DSSS_MULTI1, 			CLM_RATE_1X2_DSSS_2, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x2_FIRST + 1,		WL_TX_POWER_CCK_CDD_S1x2_FIRST + 1, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX, 			 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST + 1,		WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST + 1},
	{"DSSS5_MULTI1", 1, 2, 		RATE_GROUP_ID_DSSS_MULTI1, 			CLM_RATE_1X2_DSSS_5_5, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x2_FIRST + 2,		WL_TX_POWER_CCK_CDD_S1x2_FIRST + 2, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX, 			 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST + 2,		WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST + 2},
	{"DSSS11_MULTI1", 1, 2, 	RATE_GROUP_ID_DSSS_MULTI1,  	 	CLM_RATE_1X2_DSSS_11, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x2_FIRST + 3,		WL_TX_POWER_CCK_CDD_S1x2_FIRST + 3, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX, 			 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST + 3,		WL_TX_POWER_CCK_20U_CDD_S1x2_FIRST + 3},
	{"OFDM6_CDD1", 1, 2, 		RATE_GROUP_ID_OFDM_CDD1, 			CLM_RATE_1X2_CDD_OFDM_6, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST, 			WL_TX_POWER_OFDM20_CDD_FIRST, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST, 		WL_TX_POWER_OFDM40_CDD_FIRST, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST,			WL_TX_POWER_20UL_OFDM_CDD_FIRST},
	{"OFDM9_CDD1", 1, 2, 		RATE_GROUP_ID_OFDM_CDD1, 			CLM_RATE_1X2_CDD_OFDM_9, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST + 1, 		WL_TX_POWER_OFDM20_CDD_FIRST + 1, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST + 1, 	WL_TX_POWER_OFDM40_CDD_FIRST + 1, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST + 1,		WL_TX_POWER_20UL_OFDM_CDD_FIRST + 1},
	{"OFDM12_CDD1", 1, 2,	 	RATE_GROUP_ID_OFDM_CDD1, 	 	 	CLM_RATE_1X2_CDD_OFDM_12, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST + 2, 		WL_TX_POWER_OFDM20_CDD_FIRST + 2, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST + 2, 	WL_TX_POWER_OFDM40_CDD_FIRST + 2, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST + 2,		WL_TX_POWER_20UL_OFDM_CDD_FIRST + 2},
	{"OFDM18_CDD1", 1, 2, 		RATE_GROUP_ID_OFDM_CDD1, 			CLM_RATE_1X2_CDD_OFDM_18, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST + 3, 		WL_TX_POWER_OFDM20_CDD_FIRST + 3, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST + 3, 	WL_TX_POWER_OFDM40_CDD_FIRST + 3, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST + 3,		WL_TX_POWER_20UL_OFDM_CDD_FIRST + 3},
	{"OFDM24_CDD1", 1, 2, 		RATE_GROUP_ID_OFDM_CDD1, 			CLM_RATE_1X2_CDD_OFDM_24, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST + 4, 		WL_TX_POWER_OFDM20_CDD_FIRST + 4, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST + 4, 	WL_TX_POWER_OFDM40_CDD_FIRST + 4, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST + 4,		WL_TX_POWER_20UL_OFDM_CDD_FIRST + 4},
	{"OFDM36_CDD1", 1, 2, 		RATE_GROUP_ID_OFDM_CDD1, 			CLM_RATE_1X2_CDD_OFDM_36, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST + 5, 		WL_TX_POWER_OFDM20_CDD_FIRST + 5, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST + 5, 	WL_TX_POWER_OFDM40_CDD_FIRST + 5, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST + 5,		WL_TX_POWER_20UL_OFDM_CDD_FIRST + 5},
	{"OFDM48_CDD1", 1, 2, 		RATE_GROUP_ID_OFDM_CDD1, 			CLM_RATE_1X2_CDD_OFDM_48, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST + 6, 		WL_TX_POWER_OFDM20_CDD_FIRST + 6, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST + 6, 	WL_TX_POWER_OFDM40_CDD_FIRST + 6, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST + 6,		WL_TX_POWER_20UL_OFDM_CDD_FIRST + 6},
	{"OFDM54_CDD1", 1, 2, 		RATE_GROUP_ID_OFDM_CDD1, 			CLM_RATE_1X2_CDD_OFDM_54, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM20_CDD_FIRST + 7, 		WL_TX_POWER_OFDM20_CDD_FIRST + 7, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_OFDM40_CDD_FIRST + 7, 	WL_TX_POWER_OFDM40_CDD_FIRST + 7, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_OFDM_CDD_FIRST + 7,		WL_TX_POWER_20UL_OFDM_CDD_FIRST + 7},
	{"MCS0_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS0, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST, 			WL_TX_POWER_20_S1x2_FIRST, 				WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST, 		WL_TX_POWER_40_S1x2_FIRST, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST,				WL_TX_POWER_20UL_S1x2_FIRST},
	{"MCS1_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS1, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST + 1, 		WL_TX_POWER_20_S1x2_FIRST + 1, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST + 1, 	WL_TX_POWER_40_S1x2_FIRST + 1, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST + 1,			WL_TX_POWER_20UL_S1x2_FIRST + 1},
	{"MCS2_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS2, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST + 2, 		WL_TX_POWER_20_S1x2_FIRST + 2, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST + 2, 	WL_TX_POWER_40_S1x2_FIRST + 2, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST + 2,			WL_TX_POWER_20UL_S1x2_FIRST + 2},
	{"MCS3_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS3, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST + 3, 		WL_TX_POWER_20_S1x2_FIRST + 3, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST + 3, 	WL_TX_POWER_40_S1x2_FIRST + 3, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST + 3,			WL_TX_POWER_20UL_S1x2_FIRST + 3},
	{"MCS4_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS4, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST + 4, 		WL_TX_POWER_20_S1x2_FIRST + 4, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST + 4, 	WL_TX_POWER_40_S1x2_FIRST + 4, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST + 4,			WL_TX_POWER_20UL_S1x2_FIRST + 4},
	{"MCS5_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS5, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST + 5, 		WL_TX_POWER_20_S1x2_FIRST + 5, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST + 5, 	WL_TX_POWER_40_S1x2_FIRST + 5, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST + 5,			WL_TX_POWER_20UL_S1x2_FIRST + 5},
	{"MCS6_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS6, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST + 6, 		WL_TX_POWER_20_S1x2_FIRST + 6, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST + 6, 	WL_TX_POWER_40_S1x2_FIRST + 6, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST + 6,			WL_TX_POWER_20UL_S1x2_FIRST + 6},
	{"MCS7_CDD1", 1, 2, 		RATE_GROUP_ID_MCS0_7_CDD1, 			CLM_RATE_1X2_CDD_MCS7, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_CDD_FIRST + 7, 		WL_TX_POWER_20_S1x2_FIRST + 7, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_CDD_FIRST + 7, 	WL_TX_POWER_40_S1x2_FIRST + 7, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S1x2_FIRST + 7,			WL_TX_POWER_20UL_S1x2_FIRST + 7},
	{"MCS0_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS0, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST, 			WL_TX_POWER_MCS20_STBC_FIRST,			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST, 		WL_TX_POWER_MCS40_STBC_FIRST,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST,				WL_TX_POWER_MCS20_STBC_FIRST},
	{"MCS1_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS1, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 1, 		WL_TX_POWER_MCS20_STBC_FIRST + 1,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST + 1, 	WL_TX_POWER_MCS40_STBC_FIRST + 1,	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 1,			WL_TX_POWER_MCS20_STBC_FIRST + 1},
	{"MCS2_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS2, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 2, 		WL_TX_POWER_MCS20_STBC_FIRST + 2,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST + 2, 	WL_TX_POWER_MCS40_STBC_FIRST + 2,	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 2,			WL_TX_POWER_MCS20_STBC_FIRST + 2},
	{"MCS3_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS3, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 3, 		WL_TX_POWER_MCS20_STBC_FIRST + 3,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST + 3, 	WL_TX_POWER_MCS40_STBC_FIRST + 3,	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 3,			WL_TX_POWER_MCS20_STBC_FIRST + 3},
	{"MCS4_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS4, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 4, 		WL_TX_POWER_MCS20_STBC_FIRST + 4,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST + 4, 	WL_TX_POWER_MCS40_STBC_FIRST + 4,	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 4,			WL_TX_POWER_MCS20_STBC_FIRST + 4},
	{"MCS5_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS5, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 5, 		WL_TX_POWER_MCS20_STBC_FIRST + 5,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST + 5, 	WL_TX_POWER_MCS40_STBC_FIRST + 5, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 5,			WL_TX_POWER_MCS20_STBC_FIRST + 5},
	{"MCS6_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS6, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 6, 		WL_TX_POWER_MCS20_STBC_FIRST + 6,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST + 6, 	WL_TX_POWER_MCS40_STBC_FIRST + 6,	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 6, 			WL_TX_POWER_MCS20_STBC_FIRST + 6},
	{"MCS7_STBC", 2, 2, 		RATE_GROUP_ID_MCS0_7_STBC, 			CLM_RATE_2X2_STBC_MCS7, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 7, 		WL_TX_POWER_MCS20_STBC_FIRST + 7,		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_STBC_FIRST + 7, 	WL_TX_POWER_MCS40_STBC_FIRST + 7,	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_STBC_FIRST + 7,			WL_TX_POWER_MCS20_STBC_FIRST + 7},
	{"MCS8", 2, 2, 				RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS8, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST, 			WL_TX_POWER_20_S2x2_FIRST, 				WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST, 		WL_TX_POWER_40_S2x2_FIRST, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST,				WL_TX_POWER_20UL_S2x2_FIRST},
	{"MCS9", 2, 2, 				RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS9, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST + 1, 		WL_TX_POWER_20_S2x2_FIRST + 1, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST + 1, 	WL_TX_POWER_40_S2x2_FIRST + 1, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST + 1,			WL_TX_POWER_20UL_S2x2_FIRST + 1},
	{"MCS10", 2, 2, 			RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS10, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST + 2, 		WL_TX_POWER_20_S2x2_FIRST + 2, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST + 2, 	WL_TX_POWER_40_S2x2_FIRST + 2, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST + 2,			WL_TX_POWER_20UL_S2x2_FIRST + 2},
	{"MCS11", 2, 2, 			RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS11, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST + 3, 		WL_TX_POWER_20_S2x2_FIRST + 3, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST + 3, 	WL_TX_POWER_40_S2x2_FIRST + 3, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST + 3,			WL_TX_POWER_20UL_S2x2_FIRST + 3},
	{"MCS12", 2, 2, 			RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS12, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST + 4, 		WL_TX_POWER_20_S2x2_FIRST + 4, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST + 4, 	WL_TX_POWER_40_S2x2_FIRST + 4, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST + 4,			WL_TX_POWER_20UL_S2x2_FIRST + 4},
	{"MCS13", 2, 2, 			RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS13, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST + 5, 		WL_TX_POWER_20_S2x2_FIRST + 5, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST + 5, 	WL_TX_POWER_40_S2x2_FIRST + 5, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST + 5,			WL_TX_POWER_20UL_S2x2_FIRST + 5},
	{"MCS14", 2, 2, 			RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS14, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST + 6, 		WL_TX_POWER_20_S2x2_FIRST + 6, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST + 6, 	WL_TX_POWER_40_S2x2_FIRST + 6, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST + 6,			WL_TX_POWER_20UL_S2x2_FIRST + 6},
	{"MCS15", 2, 2, 			RATE_GROUP_ID_MCS8_15, 				CLM_RATE_2X2_SDM_MCS15, 	WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS20_SDM_FIRST + 7, 		WL_TX_POWER_20_S2x2_FIRST + 7, 			WL_UNSUPPORTED_IDX,						WL_TX_POWER_MCS40_SDM_FIRST + 7, 	WL_TX_POWER_40_S2x2_FIRST + 7, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_20UL_S2x2_FIRST + 7,			WL_TX_POWER_20UL_S2x2_FIRST + 7},
	{"DSSS1_MULTI2", 1, 3, 		RATE_GROUP_ID_DSSS_MULTI2, 			CLM_RATE_1X3_DSSS_1, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x3_FIRST, 		WL_TX_POWER_CCK_CDD_S1x3_FIRST, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_CCK_20U_CDD_S1x3_FIRST},
	{"DSSS2_MULTI2", 1, 3, 		RATE_GROUP_ID_DSSS_MULTI2, 			CLM_RATE_1X3_DSSS_2, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x3_FIRST + 1,		WL_TX_POWER_CCK_CDD_S1x3_FIRST + 1,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_CCK_20U_CDD_S1x3_FIRST + 1},
	{"DSSS5_MULTI2", 1, 3, 		RATE_GROUP_ID_DSSS_MULTI2, 			CLM_RATE_1X3_DSSS_5_5, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x3_FIRST + 2,		WL_TX_POWER_CCK_CDD_S1x3_FIRST + 2,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_CCK_20U_CDD_S1x3_FIRST + 2},
	{"DSSS11_MULTI2", 1, 3, 	RATE_GROUP_ID_DSSS_MULTI2,  	 	CLM_RATE_1X3_DSSS_11, 		WL_UNSUPPORTED_IDX,						WL_TX_POWER_CCK_CDD_S1x3_FIRST + 3,		WL_TX_POWER_CCK_CDD_S1x3_FIRST + 3,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_CCK_20U_CDD_S1x3_FIRST + 3},
	{"OFDM6_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_6, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"OFDM9_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_9, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"OFDM12_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_12, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"OFDM18_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_18, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 	WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"OFDM24_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_24, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"OFDM36_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_36, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"OFDM48_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_48, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"OFDM54_CDD2", 1, 3, 		RATE_GROUP_ID_OFDM_CDD2, 			CLM_RATE_1X3_CDD_OFDM_54, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,  	 	 	 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS0_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS0, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST, 				WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST},
	{"MCS1_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS1, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST + 1,			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST + 1,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST + 1},
	{"MCS2_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS2, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST + 2,			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST + 2,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST + 2},
	{"MCS3_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS3, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST + 3,			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST + 3,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST + 3},
	{"MCS4_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS4, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST + 4,			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST + 4,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST + 4},
	{"MCS5_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS5, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST + 5,			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST + 5,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST + 5},
	{"MCS6_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS6, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST + 6,			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST + 6,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST + 6},
	{"MCS7_CDD2", 1, 3, 		RATE_GROUP_ID_MCS0_7_CDD2, 			CLM_RATE_1X3_CDD_MCS7, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S1x3_FIRST + 7,			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_TX_POWER_40_S1x3_FIRST + 7,		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S1x3_FIRST + 7},
	{"MCS0_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS0, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS1_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS1, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS2_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS2, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS3_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS3, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS4_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS4, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS5_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS5, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS6_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS6, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS7_STBC_SPEXP1", 2, 3, 	RATE_GROUP_ID_MCS0_7_STBC_SPEXP1, 	CLM_RATE_2X3_STBC_MCS7, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 				WL_UNSUPPORTED_IDX,					WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_UNSUPPORTED_IDX},
	{"MCS8_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS8, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST, 				WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST},
	{"MCS9_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS9, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST + 1, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST + 1, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST + 1},
	{"MCS10_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS10, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST + 2, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST + 2, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST + 2},
	{"MCS11_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS11, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST + 3,   		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST + 3, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST + 3},
	{"MCS12_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS12, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST + 4,   		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST + 4, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST + 4},
	{"MCS13_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS13, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST + 5,   		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST + 5, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST + 5},
	{"MCS14_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS14, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST + 6,   		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST + 6, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST + 6},
	{"MCS15_SPEXP1", 2, 3, 		RATE_GROUP_ID_MCS8_15_SPEXP1, 		CLM_RATE_2X3_SDM_MCS15, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S2x3_FIRST + 7,   		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S2x3_FIRST + 7, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S2x3_FIRST + 7},
	{"MCS16", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS16, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST, 		 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST},
	{"MCS17", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS17, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST + 1, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST + 1, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST + 1},
	{"MCS18", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS18, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST + 2, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST + 2, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST + 2},
	{"MCS19", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS19, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST + 3, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST + 3, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST + 3},
	{"MCS20", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS20, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST + 4, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST + 4, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST + 4},
	{"MCS21", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS21, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST + 5, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST + 5, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST + 5},
	{"MCS22", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS22, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST + 6, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST + 6, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST + 6},
	{"MCS23", 3, 3, 			RATE_GROUP_ID_MCS16_23, 			CLM_RATE_3X3_SDM_MCS23, 	WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX, 					WL_TX_POWER_20_S3x3_FIRST + 7, 			WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,					WL_TX_POWER_40_S3x3_FIRST + 7, 		WL_UNSUPPORTED_IDX,						WL_UNSUPPORTED_IDX,							WL_TX_POWER_20UL_S3x3_FIRST + 7}
};


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _WLU_RATES_MATRIX_H_ */
